# Allow user to enter data about school attendance daily.
print("Designed By Thepros Multi Vison Ent.")
print("Est. 1982")
print("Founder",  "Mr. Theophilus Gyarbeng")
while True:
    School_Name = (input("Enter the school name:"))
    print(School_Name)
    Applicant_Name = (input("Enter the name of applicant:"))
    print(Applicant_Name)
    Date_birth = int(input("Enter the date of birth:"))
    print(Date_birth)
    Sex_pupil = (input("Enter the sex of the pupil:"))
    print(Sex_pupil)
    father_name = (input("Enter the father name of the pupil:"))
    print (father_name)
    occupation_of_father = (input("State the occupation of the father:"))
    print(occupation_of_father)
    father_age = int(input("Enter the age of the pupils' father:"))
    print(father_age)
    level_education = (input("Enter the hiesght educational level of the father:"))
    print(level_education)
    home_town = (input ("Enter the home town of the father:"))
    print(home_town)
    marrital_status = (input("Enter the marrital status of the father:"))
    print(marrital_status)
    
    mother_name = (input("Enter the father name of the pupil:"))
    print (mother_name)
    occupation_of_mother = (input("State the occupation of the mother:"))
    print(occupation_of_father)
    mother_age = int(input("Enter the age of the pupils' mother:"))
    print(father_age)
    level_education = (input("Enter the hiesght educational level of the mother:"))
    print(level_education)
    home_town = (input ("Enter the home town of the mother:"))
    print(home_town)
    marrital_status = (input("Enter the marrital status of the mother:"))
    print(marrital_status)
    
                 