print("Damtse Polling Station Executives")
print("2021")
while True:
    Polling_station_code = (input("The accurate seven digit alphanumeric code:"))
    print(Polling_station_code)
    Polling_station_name = (input("Enter the full polling station namte:"))
    print(Polling_station_name)
    names = (input("Enter your valid name:"))
    print(names)
    positions = (input("Enter your current position:"))
    print(positions)
    GPS_code = (input("Enter your valid gps code:"))
    print(GPS_code)
    house_number = (input("Enter your current residential address:"))
    print(house_number)
    party_card = (input("Enter your valid party card id number:"))
    print(party_card)
    contact_numbers = (input("Enter your personal phone number:"))
    print(contact_numbers)
        
    